package com.careeros.job.application.ingestion;

import com.careeros.company.domain.*;import com.careeros.job.application.*;import com.careeros.provider.application.*;import com.careeros.provider.domain.*;import io.micrometer.core.instrument.simple.SimpleMeterRegistry;import org.junit.jupiter.api.Test;import org.springframework.data.domain.*;import java.time.LocalDate;import java.util.*;import static org.assertj.core.api.Assertions.assertThat;
class ProviderFallbackTest {
 @Test void stopsAtFirstSuccessfulFallback(){var company=Company.create("Example","https://example.test",AtsType.OTHER,Priority.HIGH,true,null);company.configureProvider(ProviderType.GENERIC_JSON,"{}",List.of(ProviderType.GENERIC_HTML,ProviderType.GENERIC_RSS));List<ProviderType>called=new ArrayList<>();JobProviderRegistry registry=type->Optional.of(new JobProvider(){public ProviderType providerType(){return type;}public List<JobPostingCommand>fetchJobs(Company c){called.add(type);if(type==ProviderType.GENERIC_JSON)throw new RuntimeException("bad json");return List.of(new JobPostingCommand("1",null,"Senior Engineer","Remote",null,true,null,null,null,"",LocalDate.now(),"https://example.test/1"));}});var service=new JobIngestionService(new FakeJobs(),new FakeCompanies(company),registry,new FakeHistory(),new SimpleMeterRegistry());var result=service.ingestAllEnabledCompanies().results().getFirst();assertThat(called).containsExactly(ProviderType.GENERIC_JSON,ProviderType.GENERIC_HTML);assertThat(result.created()).isEqualTo(1);}
 static class FakeJobs extends JobPostingService{FakeJobs(){super(null,null);}@Override public com.careeros.job.domain.JobPosting create(JobPostingCommand c){return null;}}
 static class FakeHistory extends SyncHistoryService{FakeHistory(){super(null);}@Override public SyncHistory record(SyncHistory h){return h;}}
 record FakeCompanies(Company company) implements CompanyRepository{public Company save(Company c){return c;}public Optional<Company>findById(UUID id){return Optional.of(company);}public boolean existsByNameIgnoreCase(String n){return false;}public Optional<Company>findByNameIgnoreCase(String n){return Optional.empty();}public Page<Company>findAll(CompanyFilter f,Pageable p){return Page.empty();}public List<Company>findAllEnabled(){return List.of(company);}public void deleteById(UUID id){}public boolean existsById(UUID id){return true;}}
}
