package com.careeros.application.domain;
public enum ApplicationStatus { WISHLIST, APPLIED, RECRUITER_CONTACTED, REFERRAL_REQUESTED, RECRUITER_SCREEN, TECHNICAL_INTERVIEW, SYSTEM_DESIGN, BEHAVIORAL, FINAL_INTERVIEW, OFFER, REJECTED, WITHDRAWN }
