package com.careeros.job.application.ingestion;

import com.careeros.common.exception.*;import com.careeros.company.domain.*;import com.careeros.job.application.*;import com.careeros.provider.application.*;import com.careeros.provider.domain.*;import io.micrometer.core.instrument.*;import org.slf4j.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.stereotype.Service;
import java.time.Instant;import java.util.*;import java.util.function.Function;import java.util.stream.Collectors;

@Service public class JobIngestionService {
 private static final Logger log=LoggerFactory.getLogger(JobIngestionService.class);private final JobPostingService jobs;private final CompanyRepository companies;private final JobProviderRegistry registry;private final SyncHistoryService history;private final MeterRegistry metrics;
 @Autowired public JobIngestionService(JobPostingService jobs,CompanyRepository companies,JobProviderRegistry registry,SyncHistoryService history,MeterRegistry metrics){this.jobs=jobs;this.companies=companies;this.registry=registry;this.history=history;this.metrics=metrics;}
 public JobIngestionService(JobPostingService jobs,CompanyRepository companies,List<AtsConnector> connectors){this.jobs=jobs;this.companies=companies;Map<ProviderType,JobProvider>map;try{map=connectors.stream().collect(Collectors.toMap(JobProvider::providerType,Function.identity()));}catch(IllegalStateException e){throw new IllegalStateException("Duplicate job provider registration",e);}this.registry=type->Optional.ofNullable(map.get(type));this.history=null;this.metrics=null;}
 public IngestionSummary ingestAllEnabledCompanies(){return IngestionSummary.of(companies.findAllEnabled().stream().map(this::ingestOneCompany).toList());}
 public IngestionSummary ingestCompany(UUID id){return IngestionSummary.of(List.of(ingestOneCompany(companies.findById(id).orElseThrow(()->ResourceNotFoundException.forId("Company",id)))));}
 private CompanyIngestionResult ingestOneCompany(Company company){List<ProviderType>chain=new ArrayList<>();if(company.getProviderType()!=null)chain.add(company.getProviderType());chain.addAll(company.getFallbackProviders());if(chain.isEmpty())return CompanyIngestionResult.unsupportedAtsType(company);List<String>errors=new ArrayList<>();for(ProviderType type:chain){Optional<JobProvider>provider=registry.resolve(type);if(provider.isEmpty()){errors.add(type+": no provider registered");continue;}Instant start=Instant.now();List<JobPostingCommand>commands;try{commands=provider.get().fetchJobs(company);}catch(Exception e){record(company,type,start,false,0,0,e.getMessage());metric(type,false,0,start);errors.add(type+": "+e.getMessage());log.warn("Provider {} failed for {}: {}",type,company.getName(),e.getMessage());continue;}int created=0,skipped=0,failed=0;for(var command:commands)try{jobs.create(command);created++;}catch(DuplicateResourceException e){skipped++;}catch(Exception e){failed++;errors.add(command.externalId()+": "+e.getMessage());}record(company,type,start,true,commands.size(),created,null);metric(type,true,commands.size(),start);return new CompanyIngestionResult(company.getId(),company.getName(),company.getAtsType(),created,skipped,failed,errors);}return new CompanyIngestionResult(company.getId(),company.getName(),company.getAtsType(),0,0,1,errors);}
 private void record(Company c,ProviderType p,Instant start,boolean success,int found,int added,String error){if(history!=null)history.record(SyncHistory.record(c,p,start,success,found,added,0,error));}
 private void metric(ProviderType p,boolean success,int found,Instant start){if(metrics==null)return;Tags tags=Tags.of("provider",p.name());metrics.counter("provider.sync.count",tags).increment();metrics.counter(success?"provider.sync.success":"provider.sync.failure",tags).increment();metrics.counter("provider.jobs.discovered",tags).increment(found);metrics.timer("provider.sync.duration",tags).record(java.time.Duration.between(start,Instant.now()));}
}
