package com.careeros.ai.infrastructure;
import com.careeros.ai.application.AIProvider;import com.fasterxml.jackson.databind.*;import org.springframework.http.client.SimpleClientHttpRequestFactory;import org.springframework.stereotype.Component;import org.springframework.web.client.RestClient;import java.util.*;
@Component public class OllamaProvider implements AIProvider{
 private final RestClient client;private final ObjectMapper json;private final OllamaProperties p;
 public OllamaProvider(RestClient.Builder b,ObjectMapper j,OllamaProperties p){var requests=new SimpleClientHttpRequestFactory();requests.setConnectTimeout(p.timeout());requests.setReadTimeout(p.timeout());client=b.baseUrl(p.baseUrl()).requestFactory(requests).build();json=j;this.p=p;}
 public String name(){return"ollama";}public boolean healthy(){try{models();return true;}catch(Exception e){return false;}}
 public List<String>models(){JsonNode n=call("GET","/api/tags",null);List<String>out=new ArrayList<>();n.path("models").forEach(x->out.add(x.path("name").asText()));return out;}
 public Generation generateJson(String model,String prompt){var body=Map.of("model",model==null?p.primaryModel():model,"prompt",prompt,"stream",false,"format","json");JsonNode response=retry(()->call("POST","/api/generate",body));try{JsonNode value=json.readTree(response.path("response").asText());List<String>b=new ArrayList<>(),w=new ArrayList<>();value.path("bullets").forEach(x->b.add(x.asText()));value.path("warnings").forEach(x->w.add(x.asText()));if(b.isEmpty())throw new IllegalArgumentException("Ollama returned no bullets");return new Generation(b,value.path("reasoning").asText(),w);}catch(Exception e){throw new IllegalStateException("Ollama returned invalid structured JSON: "+e.getMessage(),e);}}
 public List<Double>embed(String model,String text){JsonNode n=retry(()->call("POST","/api/embed",Map.of("model",model==null?p.embeddingModel():model,"input",text)));List<Double>v=new ArrayList<>();n.path("embeddings").path(0).forEach(x->v.add(x.asDouble()));return v;}
 private JsonNode call(String method,String path,Object body){return method.equals("GET")?client.get().uri(path).retrieve().body(JsonNode.class):client.post().uri(path).body(body).retrieve().body(JsonNode.class);}private<T>T retry(java.util.concurrent.Callable<T>c){Exception last=null;for(int i=0;i<3;i++)try{return c.call();}catch(Exception e){last=e;try{Thread.sleep(200L*(1L<<i));}catch(InterruptedException x){Thread.currentThread().interrupt();throw new IllegalStateException("Ollama request interrupted",x);}}throw new IllegalStateException("Ollama unavailable at "+p.baseUrl()+": "+last.getMessage(),last);}
}
