package com.careeros.application.web;
import com.careeros.application.application.JobApplicationService; import com.careeros.application.domain.*; import com.careeros.common.web.PageResponse;
import io.swagger.v3.oas.annotations.tags.Tag; import jakarta.validation.Valid; import jakarta.validation.constraints.NotNull; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/applications") @Tag(name="Applications") public class JobApplicationController {
 private final JobApplicationService s; public JobApplicationController(JobApplicationService s){this.s=s;}
 @PostMapping public ResponseEntity<Response> create(@Valid @RequestBody Request r){var a=s.create(cmd(r));return ResponseEntity.status(201).body(out(a));} @GetMapping("/{id}") public Response get(@PathVariable UUID id){return out(s.get(id));} @GetMapping public PageResponse<Response> list(Pageable p){return PageResponse.from(s.list(p),this::out);} @PutMapping("/{id}") public Response update(@PathVariable UUID id,@Valid @RequestBody Request r){return out(s.update(id,cmd(r)));} @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void delete(@PathVariable UUID id){s.delete(id);}
 private JobApplicationService.Command cmd(Request r){return new JobApplicationService.Command(r.jobPostingId,r.status,r.appliedDate,r.followUpDate,r.interviewDate,r.notes,r.resumeVersion,r.referralName,r.recruiterName,r.jobLink);} private Response out(JobApplication a){return new Response(a.getId(),a.getJob().getId(),a.getStatus(),a.getAppliedDate(),a.getFollowUpDate(),a.getInterviewDate(),a.getNotes(),a.getResumeVersion(),a.getReferralName(),a.getRecruiterName(),a.getJobLink(),a.getUpdatedAt());}
 public record Request(@NotNull UUID jobPostingId,@NotNull ApplicationStatus status,LocalDate appliedDate,LocalDate followUpDate,LocalDate interviewDate,String notes,String resumeVersion,String referralName,String recruiterName,String jobLink){} public record Response(UUID id,UUID jobPostingId,ApplicationStatus status,LocalDate appliedDate,LocalDate followUpDate,LocalDate interviewDate,String notes,String resumeVersion,String referralName,String recruiterName,String jobLink,java.time.Instant lastUpdated){}
}
