import{useState}from'react';
import{useQueryClient}from'@tanstack/react-query';
import{motion}from'framer-motion';
import{Building2,Calendar,ExternalLink,GripVertical,MapPin,Plus,Trash2,UserRound}from'lucide-react';
import{getListApplicationsQueryKey,useDeleteApplication,useListApplications,useUpdateApplication}from'@/api/generated/applications/applications';
import{useGetJob}from'@/api/generated/jobs/jobs';
import type{Application,ApplicationStatus}from'@/api/generated/model';
import{Page}from'@/components/page';
import{Badge,Button,ErrorState,Modal,Skeleton}from'@/components/ui';
import{formatDate}from'@/lib/utils';
import{toast}from'sonner';

const stages:[ApplicationStatus,string][]=[['WISHLIST','Wishlist'],['APPLIED','Applied'],['RECRUITER_CONTACTED','Recruiter Contacted'],['REFERRAL_REQUESTED','Referral Requested'],['RECRUITER_SCREEN','Recruiter Screen'],['TECHNICAL_INTERVIEW','Technical'],['SYSTEM_DESIGN','System Design'],['BEHAVIORAL','Behavioral'],['FINAL_INTERVIEW','Final'],['OFFER','Offer'],['REJECTED','Rejected'],['WITHDRAWN','Withdrawn']];

export default function ApplicationsPage(){
 const q=useListApplications({size:200}),qc=useQueryClient();
 const update=useUpdateApplication({mutation:{onMutate:async({id,data})=>{await qc.cancelQueries({queryKey:getListApplicationsQueryKey({size:200})});const old=q.data;qc.setQueryData(getListApplicationsQueryKey({size:200}),(v:typeof old)=>v?{...v,data:{...v.data,content:v.data.content?.map(a=>a.id===id?{...a,status:data.status}:a)}}:v);return{old}},onError:(_e,_v,c)=>{qc.setQueryData(getListApplicationsQueryKey({size:200}),c?.old);toast.error('Could not move application')},onSettled:()=>qc.invalidateQueries({queryKey:getListApplicationsQueryKey()})}});
 const[dragged,setDragged]=useState<Application|null>(null),[selected,setSelected]=useState<Application|null>(null);
 const changeStatus=(item:Application,status:ApplicationStatus)=>{if(item.status===status)return;update.mutate({id:item.id!,data:{...item,jobPostingId:item.jobPostingId!,status}})};const move=(status:ApplicationStatus)=>{if(!dragged)return;changeStatus(dragged,status);setDragged(null)};
 return <Page title="Applications" description="Move opportunities through your hiring pipeline" actions={<Button className="btn-primary"><Plus className="size-3"/>Add application</Button>}>
  {q.isError?<ErrorState retry={()=>q.refetch()}/>:q.isLoading?<div className="flex gap-3 overflow-hidden">{stages.slice(0,5).map(x=><Skeleton key={x[0]} className="h-[65vh] min-w-72"/>)}</div>:<div className="flex gap-4 overflow-x-auto pb-4" aria-label="Application board">{stages.map(([status,label])=>{const cards=q.data?.data.content?.filter(a=>a.status===status)??[];return <section key={status} className="w-80 shrink-0 rounded-lg bg-zinc-100/80 p-2.5 dark:bg-zinc-900/60" onDragOver={e=>e.preventDefault()} onDrop={()=>move(status)}><header className="flex h-10 items-center px-1 text-xs font-semibold"><span>{label}</span><Badge className="ml-2">{cards.length}</Badge></header><div className="min-h-44 space-y-2.5">{cards.map(a=><ApplicationCard key={a.id} item={a} drag={()=>setDragged(a)} open={()=>setSelected(a)} move={status=>changeStatus(a,status)}/>)}{cards.length===0&&<div className="grid h-28 place-items-center rounded-md border border-dashed text-xs muted">Drop here</div>}</div></section>})}</div>}
  {selected&&<ApplicationDetails item={selected} close={()=>setSelected(null)}/>}
 </Page>;
}

function ApplicationCard({item,drag,open,move}:{item:Application;drag:()=>void;open:()=>void;move:(status:ApplicationStatus)=>void}){
 return <motion.article layout draggable tabIndex={0} role="button" onDragStart={drag} onClick={open} onKeyDown={e=>(e.key==='Enter'||e.key===' ')&&open()} className="cursor-pointer rounded-lg border bg-white p-4 shadow-sm transition-shadow hover:shadow-md focus:outline-none focus:ring-2 focus:ring-indigo-500 active:cursor-grabbing dark:bg-zinc-950" aria-label={`View ${item.jobTitle??'job'} details`}>
  <div className="flex items-start gap-2.5"><GripVertical className="mt-1 size-3.5 shrink-0 cursor-grab muted"/><div className="min-w-0 flex-1"><p className="line-clamp-2 text-sm font-semibold leading-5">{item.jobTitle??`Job ${item.jobPostingId?.slice(0,8)}`}</p><p className="mt-1 flex items-center gap-1.5 text-xs font-medium muted"><Building2 className="size-3"/>{item.company??'Unknown company'}</p></div>{item.jobLink&&<a href={item.jobLink} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()} className="muted hover:text-indigo-600" aria-label={`Open ${item.jobTitle??'job'} application`}><ExternalLink className="size-3.5"/></a>}</div>
  <div className="mt-3 space-y-1.5 border-t pt-3 text-xs muted">{(item.location||item.remote)&&<p className="flex items-center gap-1.5"><MapPin className="size-3"/><span className="line-clamp-1">{item.location||'Remote'}</span>{item.remote&&<Badge>Remote</Badge>}</p>}{item.appliedDate&&<p className="flex items-center gap-1.5"><Calendar className="size-3"/>Applied {formatDate(item.appliedDate)}</p>}{item.recruiterName&&<p className="flex items-center gap-1.5"><UserRound className="size-3"/>{item.recruiterName}</p>}{item.followUpDate&&<p className="flex items-center gap-1.5 text-amber-600"><Calendar className="size-3"/>Follow up {formatDate(item.followUpDate)}</p>}{item.notes&&<p className="line-clamp-2 pt-1 italic">{item.notes}</p>}</div><label className="mt-3 block border-t pt-3 text-[10px] font-medium uppercase tracking-wide muted">Move to<select className="input mt-1.5 w-full text-xs normal-case" value={item.status} onPointerDown={e=>e.stopPropagation()} onClick={e=>e.stopPropagation()} onChange={e=>{e.stopPropagation();move(e.target.value as ApplicationStatus)}}>{stages.map(([status,label])=><option value={status} key={status}>{label}</option>)}</select></label>
 </motion.article>;
}

function ApplicationDetails({item,close}:{item:Application;close:()=>void}){
 const qc=useQueryClient();const remove=useDeleteApplication({mutation:{onSuccess:()=>{qc.invalidateQueries();close();toast.success('Application removed')},onError:()=>toast.error('Could not remove application')}});
 const job=useGetJob(item.jobPostingId??'',{query:{enabled:!!item.jobPostingId}}),details=job.data?.data;
 return <Modal open onOpenChange={value=>!value&&close()} title={item.jobTitle??'Job details'} description={item.company} className="max-w-3xl">
  {job.isLoading?<div className="space-y-2"><Skeleton className="h-5 w-full"/><Skeleton className="h-5 w-11/12"/><Skeleton className="h-40 w-full"/></div>:job.isError?<ErrorState retry={()=>job.refetch()}/>:details?<div><div className="grid gap-2 text-sm sm:grid-cols-2"><Info label="Application status" value={item.status?.replaceAll('_',' ')??'Unknown'}/><Info label="Applied" value={formatDate(item.appliedDate)}/><Info label="Location" value={details.location??'Not specified'}/><Info label="Employment" value={details.employmentType?.replaceAll('_',' ')??'Not specified'}/><Info label="Workplace" value={details.remote?'Remote':'On-site or hybrid'}/><Info label="Posted" value={formatDate(details.postedDate)}/></div><div className="mt-5 flex gap-2"><a className="btn btn-primary" href={item.jobLink??details.applyUrl} target="_blank" rel="noreferrer">Open application <ExternalLink className="size-3"/></a><Button className="ml-auto text-red-600" disabled={remove.isPending} onClick={()=>confirm(`Remove ${item.jobTitle??'this application'} from tracking?`)&&remove.mutate({id:item.id!})}><Trash2 className="size-3"/>{remove.isPending?'Removing…':'Remove application'}</Button></div><section className="mt-6 border-t pt-5"><h3 className="font-semibold">Job description</h3><div className="mt-3 whitespace-pre-line text-sm leading-6 text-zinc-700 dark:text-zinc-300">{plainText(details.description)||'No job description was provided by this source.'}</div></section></div>:null}
 </Modal>;
}

function Info({label,value}:{label:string;value:string}){return <div className="rounded-md border p-3"><p className="text-[10px] font-medium uppercase tracking-wide muted">{label}</p><p className="mt-1">{value}</p></div>}
function plainText(value?:string){if(!value)return'';const doc=new DOMParser().parseFromString(value,'text/html');doc.querySelectorAll('br').forEach(x=>x.replaceWith('\n'));doc.querySelectorAll('p,li,h1,h2,h3,h4,div').forEach(x=>x.append('\n'));return(doc.body.textContent??'').replace(/\n[ \t]+/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
