import{useMemo,useState}from'react';
import{flexRender,getCoreRowModel,getFilteredRowModel,getPaginationRowModel,getSortedRowModel,useReactTable,type ColumnDef,type VisibilityState}from'@tanstack/react-table';
import{AnimatePresence,motion}from'framer-motion';
import{Bookmark,ChevronLeft,ChevronRight,Columns3,Copy,ExternalLink,MapPin,Search,SlidersHorizontal,X}from'lucide-react';
import{toast}from'sonner';
import{useGetJobTimeline}from'@/api/generated/discovery/discovery';
import type{JobSummary}from'@/api/generated/model';
import{Page}from'@/components/page';
import{Badge,Button,ErrorState,Modal,Skeleton}from'@/components/ui';
import{formatDate,scoreTone}from'@/lib/utils';

const columns:ColumnDef<JobSummary>[]=[{accessorKey:'company',header:'Company',cell:i=><span className="font-medium">{i.getValue()as string}</span>},{accessorKey:'title',header:'Title',cell:i=><span className="font-medium">{i.getValue()as string}</span>},{accessorKey:'overallScore',header:'Match',cell:i=><Badge className={scoreTone(i.getValue()as number)}>{i.getValue()as number}%</Badge>},{accessorKey:'location',header:'Location'},{accessorKey:'remote',header:'Remote',cell:i=>i.getValue()?<Badge>Remote</Badge>:'—'},{accessorKey:'postedDate',header:'Posted',cell:i=>formatDate(i.getValue()as string)},{id:'status',header:'Status',cell:()=><span className="muted">New</span>}];

export default function JobsPage(){
 const[search,setSearch]=useState('');const[selected,setSelected]=useState<JobSummary|null>(null);const[visibility,setVisibility]=useState<VisibilityState>({});
 const[minimumScore,setMinimumScore]=useState(60);const[remoteOnly,setRemoteOnly]=useState(false);const[filtersOpen,setFiltersOpen]=useState(false);const[columnsOpen,setColumnsOpen]=useState(false);
 const q=useGetJobTimeline({period:'LAST_30_DAYS',size:100,minimumScore,remote:remoteOnly||undefined});const data=useMemo(()=>q.data?.data.content??[],[q.data]);
 const table=useReactTable({data,columns,state:{globalFilter:search,columnVisibility:visibility},onGlobalFilterChange:setSearch,onColumnVisibilityChange:setVisibility,getCoreRowModel:getCoreRowModel(),getFilteredRowModel:getFilteredRowModel(),getSortedRowModel:getSortedRowModel(),getPaginationRowModel:getPaginationRowModel(),initialState:{pagination:{pageSize:20}}});
 return <Page title="Jobs" description="Discover and prioritize opportunities across every source" actions={<Button onClick={()=>toast.info('Create reusable presets from Saved Searches')}><Bookmark className="size-3"/>Save preset</Button>}>
  <div className="panel overflow-hidden"><div className="flex flex-wrap items-center gap-2 border-b p-3"><label className="relative min-w-52 flex-1 max-w-md"><Search className="absolute left-2.5 top-2 size-3.5 muted"/><input className="input w-full pl-8" placeholder="Search company or title…" value={search} onChange={e=>setSearch(e.target.value)} aria-label="Search jobs"/></label><Button onClick={()=>setFiltersOpen(true)}><SlidersHorizontal className="size-3"/>Filters{(minimumScore!==60||remoteOnly)&&<Badge>Active</Badge>}</Button><Button onClick={()=>setColumnsOpen(true)}><Columns3 className="size-3"/>Columns</Button><span className="ml-auto text-xs muted">{table.getFilteredRowModel().rows.length} jobs</span></div>
  {q.isError?<ErrorState retry={()=>q.refetch()}/>:q.isLoading?<div className="space-y-1 p-3">{Array.from({length:10},(_,i)=><Skeleton key={i} className="h-10"/>)}</div>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-zinc-50 text-xs muted dark:bg-zinc-900/50">{table.getHeaderGroups().map(h=><tr key={h.id}>{h.headers.map(x=><th key={x.id} className="h-9 whitespace-nowrap px-3 font-medium"><button onClick={x.column.getToggleSortingHandler()}>{flexRender(x.column.columnDef.header,x.getContext())}</button></th>)}</tr>)}</thead><tbody className="divide-y">{table.getRowModel().rows.map(r=><tr key={r.id} tabIndex={0} onClick={()=>setSelected(r.original)} onKeyDown={e=>e.key==='Enter'&&setSelected(r.original)} className="cursor-pointer hover:bg-zinc-50 focus:bg-zinc-50 dark:hover:bg-zinc-900/60">{r.getVisibleCells().map(c=><td key={c.id} className="max-w-72 truncate px-3 py-2.5">{flexRender(c.column.columnDef.cell,c.getContext())}</td>)}</tr>)}</tbody></table></div>}
  <footer className="flex h-12 items-center border-t px-3"><span className="text-xs muted">Page {table.getState().pagination.pageIndex+1} of {Math.max(1,table.getPageCount())}</span><div className="ml-auto flex gap-1"><Button onClick={()=>table.previousPage()} disabled={!table.getCanPreviousPage()} aria-label="Previous page"><ChevronLeft className="size-3"/></Button><Button onClick={()=>table.nextPage()} disabled={!table.getCanNextPage()} aria-label="Next page"><ChevronRight className="size-3"/></Button></div></footer></div>
  <Modal open={filtersOpen} onOpenChange={setFiltersOpen} title="Job filters" description="Filters are applied before server-side pagination."><div className="space-y-5"><label className="block text-sm font-medium">Minimum match score <b className="float-right">{minimumScore}%</b><input className="mt-3 w-full accent-indigo-600" type="range" min="0" max="100" step="5" value={minimumScore} onChange={e=>setMinimumScore(Number(e.target.value))}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={remoteOnly} onChange={e=>setRemoteOnly(e.target.checked)}/>Remote positions only</label><div className="flex justify-between border-t pt-4"><Button onClick={()=>{setMinimumScore(60);setRemoteOnly(false)}}>Reset</Button><Button className="btn-primary" onClick={()=>setFiltersOpen(false)}>View results</Button></div></div></Modal>
  <Modal open={columnsOpen} onOpenChange={setColumnsOpen} title="Visible columns" description="Choose the information shown in the jobs table."><div className="space-y-2">{table.getAllLeafColumns().map(c=><label className="flex items-center justify-between rounded-md border p-3 text-sm" key={c.id}><span>{typeof c.columnDef.header==='string'?c.columnDef.header:c.id}</span><input type="checkbox" checked={c.getIsVisible()} disabled={!c.getCanHide()} onChange={c.getToggleVisibilityHandler()}/></label>)}</div></Modal>
  <AnimatePresence>{selected&&<JobDrawer job={selected} close={()=>setSelected(null)}/>}</AnimatePresence>
 </Page>
}

function JobDrawer({job,close}:{job:JobSummary;close:()=>void}){return <><motion.button aria-label="Close job details" className="fixed inset-0 z-30 bg-black/25" onClick={close} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.aside role="dialog" aria-label={`${job.title} details`} className="fixed inset-y-0 right-0 z-40 w-full max-w-xl overflow-y-auto border-l bg-white shadow-2xl dark:bg-zinc-950" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}}><header className="sticky top-0 flex h-14 items-center border-b bg-inherit px-4"><span className="text-xs font-medium muted">JOB DETAILS</span><Button className="ml-auto border-0 px-2" onClick={close}><X className="size-4"/></Button></header><div className="p-6"><p className="muted">{job.company}</p><h2 className="mt-1 text-xl font-semibold">{job.title}</h2><div className="mt-3 flex flex-wrap gap-2"><Badge className={scoreTone(job.overallScore)}>{job.overallScore}% match</Badge>{job.remote&&<Badge>Remote</Badge>}<span className="inline-flex items-center gap-1 muted"><MapPin className="size-3"/>{job.location}</span></div><div className="mt-6 flex gap-2"><Button className="btn-primary flex-1">Apply <ExternalLink className="size-3"/></Button><Button><Bookmark className="size-3"/>Save</Button><Button onClick={()=>{navigator.clipboard.writeText(location.href);toast.success('Link copied')}}><Copy className="size-3"/></Button></div><section className="mt-8"><h3 className="font-semibold">Why this matches</h3><div className="mt-3 grid grid-cols-2 gap-2">{[['Role',job.roleScore],['Technology',job.technologyScore],['Location',job.locationScore],['Company',job.companyPriorityScore],['Recency',job.recencyScore]].map(([n,s])=><div className="rounded-md border p-3" key={n}><div className="flex justify-between text-xs"><span className="muted">{n}</span><b>{s}%</b></div><div className="mt-2 h-1 rounded bg-zinc-100 dark:bg-zinc-800"><div className="h-full rounded bg-indigo-500" style={{width:`${s}%`}}/></div></div>)}</div><ul className="mt-4 space-y-2 text-sm muted">{job.matchExplanation?.map(x=><li key={x}>• {x}</li>)}</ul></section></div></motion.aside></>}
