import{useMemo,useState}from'react';
import{useQueryClient}from'@tanstack/react-query';
import{Archive,ArrowUpDown,Download,FileText,GitCompareArrows,RotateCcw,Search,ShieldCheck}from'lucide-react';
import{archiveResume,useArchiveResume,useGetResumeHealth,useListResumes,useRestoreResume}from'@/api/generated/resumes/resumes';
import type{ResumeVersion}from'@/api/generated/model';
import{Page}from'@/components/page';
import{Badge,Button,EmptyState,ErrorState,Modal,Skeleton}from'@/components/ui';
import{formatDate}from'@/lib/utils';
import{toast}from'sonner';

type ArchiveFilter='ACTIVE'|'ARCHIVED'|'ALL';
type SortOption='NEWEST'|'OLDEST'|'VERSION_DESC'|'JOB_ASC';

export default function ResumesPage(){
 const client=useQueryClient(),q=useListResumes({size:100}),health=useGetResumeHealth(),versions=q.data?.data.content??[];
 const[query,setQuery]=useState(''),[archiveFilter,setArchiveFilter]=useState<ArchiveFilter>('ACTIVE'),[validation,setValidation]=useState('ALL'),[sort,setSort]=useState<SortOption>('NEWEST');
 const[selectedIds,setSelectedIds]=useState<string[]>([]),[compareOpen,setCompareOpen]=useState(false),[bulkPending,setBulkPending]=useState(false);
 const refresh=()=>client.invalidateQueries();
 const archive=useArchiveResume({mutation:{onSuccess:()=>{refresh();toast.success('Resume archived')}}}),restore=useRestoreResume({mutation:{onSuccess:()=>{refresh();toast.success('Resume restored')}}});
 const validations=useMemo(()=>[...new Set(versions.map(v=>v.validationResult??v.status).filter(Boolean))].sort(),[versions]);
 const visible=useMemo(()=>versions.filter(v=>archiveFilter==='ALL'||(archiveFilter==='ARCHIVED'?v.archived:!v.archived)).filter(v=>validation==='ALL'||(v.validationResult??v.status)===validation).filter(v=>`${v.jobTitle??''} ${v.modelUsed??''} ${v.status??''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sortVersions(a,b,sort)),[versions,archiveFilter,validation,query,sort]);
 const selected=versions.filter(v=>v.id&&selectedIds.includes(v.id));
 const selectableVisible=visible.map(v=>v.id).filter((id):id is string=>!!id),allVisibleSelected=selectableVisible.length>0&&selectableVisible.every(id=>selectedIds.includes(id));
 const toggle=(id?:string)=>id&&setSelectedIds(items=>items.includes(id)?items.filter(value=>value!==id):[...items,id]);
 const toggleVisible=()=>setSelectedIds(items=>allVisibleSelected?items.filter(id=>!selectableVisible.includes(id)):[...new Set([...items,...selectableVisible])]);
 const bulkArchive=async()=>{const targets=selected.filter(v=>!v.archived&&v.id);if(!targets.length)return;setBulkPending(true);try{for(const version of targets)await archiveResume(version.id!);setSelectedIds([]);await refresh();toast.success(`${targets.length} resume${targets.length===1?'':'s'} archived`)}catch(error){toast.error(error instanceof Error?error.message:'Could not archive selected resumes');await refresh()}finally{setBulkPending(false)}};
 return <Page title="Resume Library" description="Versioned, locally generated resumes tied to CareerOS jobs">
  <div className="mb-4 flex items-center gap-3 rounded-lg border border-emerald-500/20 bg-emerald-50 p-3 text-sm text-emerald-800 dark:bg-emerald-950/20 dark:text-emerald-300"><ShieldCheck className="size-5"/><div><b>Private by design</b><p className="text-xs opacity-80">Resume processing stays local through Ollama, python-docx, and LibreOffice.</p></div><Badge className="ml-auto">{health.data?.data.healthy?'Ollama ready':'Ollama unavailable'}</Badge></div>
  <div className="panel mb-4 flex flex-wrap items-center gap-2 p-3"><label className="relative min-w-56 flex-1"><Search className="absolute left-2.5 top-2 size-3.5 muted"/><input className="input w-full pl-8" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search job, model, or status…" aria-label="Search resumes"/></label><select className="input" value={archiveFilter} onChange={e=>setArchiveFilter(e.target.value as ArchiveFilter)} aria-label="Archive filter"><option value="ACTIVE">Active</option><option value="ARCHIVED">Archived</option><option value="ALL">All files</option></select><select className="input" value={validation} onChange={e=>setValidation(e.target.value)} aria-label="Validation filter"><option value="ALL">All validations</option>{validations.map(value=><option key={value} value={value}>{value?.replaceAll('_',' ')}</option>)}</select><label className="relative"><ArrowUpDown className="pointer-events-none absolute left-2.5 top-2 size-3.5 muted"/><select className="input pl-8" value={sort} onChange={e=>setSort(e.target.value as SortOption)} aria-label="Sort resumes"><option value="NEWEST">Newest first</option><option value="OLDEST">Oldest first</option><option value="VERSION_DESC">Highest version</option><option value="JOB_ASC">Job title A–Z</option></select></label></div>
  {selected.length>0&&<div className="mb-3 flex flex-wrap items-center gap-2 rounded-md border bg-zinc-50 px-3 py-2 text-sm dark:bg-zinc-900"><b>{selected.length} selected</b><Button disabled={selected.length!==2} onClick={()=>setCompareOpen(true)}><GitCompareArrows className="size-3"/>Compare</Button><Button disabled={bulkPending||selected.every(v=>v.archived)} onClick={bulkArchive}><Archive className="size-3"/>{bulkPending?'Archiving…':'Archive selected'}</Button><Button className="ml-auto" onClick={()=>setSelectedIds([])}>Clear</Button></div>}
  {q.isError?<ErrorState retry={()=>q.refetch()}/>:q.isLoading?<Skeleton className="h-64"/>:versions.length===0?<div className="panel"><EmptyState icon={<FileText/>} title="No tailored resumes yet" description="Open a job and choose Generate Tailored Resume."/></div>:visible.length===0?<div className="panel"><EmptyState icon={<Search/>} title="No matching resumes" description="Adjust your search or filters to see more files."/></div>:<div className="panel overflow-x-auto"><div className="grid min-w-[860px] grid-cols-[2rem_5rem_1fr_8rem_8rem_10rem] items-center gap-3 border-b bg-zinc-50 px-4 py-2 text-xs font-medium muted dark:bg-zinc-900"><input type="checkbox" checked={allVisibleSelected} onChange={toggleVisible} aria-label="Select all visible resumes"/><span>Version</span><span>Job</span><span>Validation</span><span>Created</span><span className="text-right">Files</span></div>{visible.map(v=><div key={v.id} className="grid min-w-[860px] grid-cols-[2rem_5rem_1fr_8rem_8rem_10rem] items-center gap-3 border-b px-4 py-3 text-sm last:border-b-0"><input type="checkbox" checked={!!v.id&&selectedIds.includes(v.id)} onChange={()=>toggle(v.id)} aria-label={`Select version ${v.versionNumber}`}/><b>v{v.versionNumber}</b><div className="min-w-0"><p className="truncate font-medium">{v.jobTitle??'Unknown job'}</p><p className="mt-0.5 text-xs muted">{v.modelUsed??'Unknown model'}{v.archived?' · Archived':''}</p></div><Badge>{(v.validationResult??v.status)?.replaceAll('_',' ')}</Badge><span className="text-xs muted">{formatDate(v.createdAt)}</span><div className="flex justify-end gap-1"><a className="btn px-2" href={`/api/resumes/${v.id}/download/docx`}><Download className="size-3"/>DOCX</a>{v.pdfGenerated&&<a className="btn px-2" href={`/api/resumes/${v.id}/download/pdf`}>PDF</a>}{v.archived?<Button className="px-2" onClick={()=>restore.mutate({id:v.id!})} aria-label={`Restore version ${v.versionNumber}`}><RotateCcw className="size-3"/></Button>:<Button className="px-2" onClick={()=>archive.mutate({id:v.id!})} aria-label={`Archive version ${v.versionNumber}`}><Archive className="size-3"/></Button>}</div></div>)}</div>}
  <Modal open={compareOpen&&selected.length===2} onOpenChange={setCompareOpen} title="Compare resume versions" description={`v${selected[0]?.versionNumber} and v${selected[1]?.versionNumber}`} className="max-w-4xl"><div className="grid gap-4 md:grid-cols-2">{selected.slice(0,2).map(v=><section key={v.id}><h3 className="mb-2 font-semibold">v{v.versionNumber} · {v.jobTitle}</h3><ul className="space-y-2 text-sm muted">{v.generatedBullets?.map((bullet,index)=><li key={`${index}-${bullet}`} className="rounded border p-2">{bullet}</li>)}</ul></section>)}</div></Modal>
 </Page>;
}

function sortVersions(a:ResumeVersion,b:ResumeVersion,sort:SortOption){if(sort==='VERSION_DESC')return(b.versionNumber??0)-(a.versionNumber??0);if(sort==='JOB_ASC')return(a.jobTitle??'').localeCompare(b.jobTitle??'');const left=new Date(a.createdAt??0).getTime(),right=new Date(b.createdAt??0).getTime();return sort==='OLDEST'?left-right:right-left}
