import{useState,type FormEvent}from'react';
import{useQueryClient}from'@tanstack/react-query';
import{Building2,ListChecks,LoaderCircle,Plus,Power,RefreshCw,Trash2}from'lucide-react';
import{toast}from'sonner';
import{useListCompanies}from'@/api/generated/companies/companies';
import{useRunCompanyIngestion}from'@/api/generated/ingestion/ingestion';
import{getListWatchlistsQueryKey,useAddCompanyToWatchlist,useCreateWatchlist,useDeleteWatchlist,useListWatchlists,useRemoveCompanyFromWatchlist,useRenameWatchlist}from'@/api/generated/watchlists/watchlists';
import type{IngestionRun,Watchlist}from'@/api/generated/model';
import{Page}from'@/components/page';
import{Badge,Button,EmptyState,ErrorState,Modal,Skeleton}from'@/components/ui';

export default function WatchlistsPage(){
 const client=useQueryClient();const q=useListWatchlists({size:100});const companiesQuery=useListCompanies({size:200});const lists=q.data?.data.content??[];
 const[creating,setCreating]=useState(false);const[managing,setManaging]=useState<Watchlist|null>(null);const[name,setName]=useState('');const[companyId,setCompanyId]=useState('');const[priority,setPriority]=useState(80);const[syncingWatchlist,setSyncingWatchlist]=useState<string|null>(null);
 const refresh=()=>client.invalidateQueries({queryKey:getListWatchlistsQueryKey({size:100})});
 const done=(message:string)=>{refresh();toast.success(message)};const fail=()=>toast.error('The watchlist could not be updated');
 const create=useCreateWatchlist({mutation:{onSuccess:()=>{done('Watchlist created');setCreating(false);setName('')},onError:fail}});
 const rename=useRenameWatchlist({mutation:{onSuccess:r=>{done('Watchlist renamed');setManaging(r.data);setName(r.data.name??'')},onError:fail}});
 const add=useAddCompanyToWatchlist({mutation:{onSuccess:r=>{done('Company added');setManaging(r.data);setCompanyId('')},onError:fail}});
 const remove=useRemoveCompanyFromWatchlist({mutation:{onSuccess:r=>{done('Company removed');setManaging(r.data)},onError:fail}});
 const del=useDeleteWatchlist({mutation:{onSuccess:()=>{done('Watchlist deleted');setManaging(null)},onError:fail}});
 const syncCompany=useRunCompanyIngestion();
 const syncWatchlist=async(w:Watchlist)=>{const companies=(w.companies??[]).filter(c=>c.enabled&&c.id);if(!companies.length){toast.info('This watchlist has no enabled companies to synchronize');return}setSyncingWatchlist(w.id??null);const runs:IngestionRun[]=[];let requestFailures=0;try{for(const company of companies){try{runs.push((await syncCompany.mutateAsync({companyId:company.id!})).data)}catch{requestFailures++}}client.invalidateQueries();const totals=runs.reduce((a,r)=>({processed:a.processed+r.companiesProcessed,created:a.created+r.totalCreated,skipped:a.skipped+r.totalSkipped,failed:a.failed+r.totalFailed}),{processed:0,created:0,skipped:0,failed:requestFailures});const message=`${totals.processed} companies · ${totals.created} new · ${totals.skipped} existing · ${totals.failed} failed`;totals.failed?toast.warning(message,{duration:8000}):toast.success(message)}finally{setSyncingWatchlist(null)}};
 const openManage=(w:Watchlist)=>{setManaging(w);setName(w.name??'');setCompanyId('')};const busy=create.isPending||rename.isPending||add.isPending||remove.isPending||del.isPending;
 const available=(companiesQuery.data?.data.content??[]).filter(c=>!managing?.companies?.some(m=>m.id===c.id));
 return <Page title="Watchlists" description="Group the companies you want to watch most closely" actions={<Button className="btn-primary" onClick={()=>{setName('');setCreating(true)}}><Plus className="size-3"/>New watchlist</Button>}>
  {q.isError?<ErrorState retry={()=>q.refetch()}/>:q.isLoading?<div className="grid gap-4 md:grid-cols-2">{[1,2,3,4].map(x=><Skeleton className="h-56" key={x}/>)}</div>:lists.length===0?<div className="panel"><EmptyState icon={<ListChecks/>} title="Build your first watchlist" description="Organize dream companies, local employers, startups, or any other group." action={<Button className="btn-primary" onClick={()=>setCreating(true)}>New watchlist</Button>}/></div>:<div className="grid gap-4 md:grid-cols-2">{lists.map(w=><section className="panel overflow-hidden" key={w.id}><header className="flex items-center border-b p-4"><div><h2 className="font-semibold">{w.name}</h2><p className="text-xs muted">{w.companies?.length??0} companies</p></div><div className="ml-auto flex gap-2"><Button disabled={syncingWatchlist!==null||!(w.companies??[]).some(c=>c.enabled&&c.id)} onClick={()=>syncWatchlist(w)}>{syncingWatchlist===w.id?<LoaderCircle className="size-3 animate-spin"/>:<RefreshCw className="size-3"/>}{syncingWatchlist===w.id?'Syncing…':'Sync'}</Button><Button onClick={()=>openManage(w)}>Manage</Button></div></header><div className="divide-y">{w.companies?.slice(0,5).map(c=><div className="flex items-center gap-3 p-3" key={c.id}><div className="grid size-8 place-items-center rounded bg-zinc-100 dark:bg-zinc-800"><Building2 className="size-4"/></div><span className="font-medium">{c.name}</span><Badge className="ml-auto">Priority {c.priority}</Badge><Power className={`size-3 ${c.enabled?'text-emerald-500':'muted'}`}/></div>)}</div></section>)}</div>}
  <Modal open={creating} onOpenChange={setCreating} title="New watchlist" description="Create a focused group of companies to monitor."><form onSubmit={(e:FormEvent)=>{e.preventDefault();if(name.trim())create.mutate({data:{name:name.trim()}})}}><label className="block text-xs font-medium">Name<input className="input mt-1.5 w-full" value={name} onChange={e=>setName(e.target.value)} placeholder="Dream Companies" autoFocus required/></label><div className="mt-5 flex justify-end gap-2"><Button type="button" onClick={()=>setCreating(false)}>Cancel</Button><Button className="btn-primary" disabled={create.isPending}>Create watchlist</Button></div></form></Modal>
  <Modal open={!!managing} onOpenChange={o=>!o&&setManaging(null)} title={`Manage ${managing?.name??'watchlist'}`} description="Rename this list or change its company membership.">{managing?.id&&<div className="space-y-5"><form className="flex gap-2" onSubmit={(e:FormEvent)=>{e.preventDefault();if(name.trim())rename.mutate({id:managing.id!,data:{name:name.trim()}})}}><input className="input flex-1" value={name} onChange={e=>setName(e.target.value)} aria-label="Watchlist name"/><Button disabled={busy}>Rename</Button></form><div><h3 className="mb-2 text-xs font-semibold uppercase muted">Companies</h3><div className="max-h-56 divide-y overflow-y-auto rounded-md border">{managing.companies?.length?managing.companies.map(c=><div key={c.id} className="flex items-center gap-2 p-2.5 text-sm"><Building2 className="size-4 muted"/><span className="flex-1">{c.name}</span><Badge>Priority {c.priority}</Badge><Button className="border-0 px-2 text-red-600" aria-label={`Remove ${c.name}`} disabled={busy} onClick={()=>c.id&&remove.mutate({id:managing.id!,companyId:c.id})}><Trash2 className="size-3"/></Button></div>):<p className="p-4 text-center text-sm muted">No companies in this watchlist.</p>}</div></div><form className="grid grid-cols-[1fr_6rem_auto] gap-2" onSubmit={(e:FormEvent)=>{e.preventDefault();if(companyId)add.mutate({id:managing.id!,companyId,data:{priority,enabled:true}})}}><select className="input min-w-0" value={companyId} onChange={e=>setCompanyId(e.target.value)} aria-label="Company"><option value="">Add company…</option>{available.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="input w-full" type="number" min="0" max="100" value={priority} onChange={e=>setPriority(Number(e.target.value))} aria-label="Priority"/><Button disabled={!companyId||busy}><Plus className="size-3"/>Add</Button></form><div className="border-t pt-4"><Button className="text-red-600" disabled={busy} onClick={()=>confirm(`Delete ${managing.name}?`)&&del.mutate({id:managing.id!})}><Trash2 className="size-3"/>Delete watchlist</Button></div></div>}</Modal>
 </Page>
}
