package com.careeros.provider.infrastructure.generic;

import com.careeros.company.domain.Company;import com.careeros.job.application.JobPostingCommand;import com.careeros.job.infrastructure.ingestion.support.*;import com.careeros.provider.application.JobProvider;import com.careeros.provider.domain.ProviderType;import com.fasterxml.jackson.databind.ObjectMapper;import org.jsoup.Jsoup;import org.jsoup.nodes.Document;import org.springframework.stereotype.Component;import org.springframework.web.client.RestClient;
import java.time.LocalDate;import java.util.*;

@Component public class GenericHtmlProvider implements JobProvider {
 private final RestClient client;private final ObjectMapper mapper;public GenericHtmlProvider(RestClient.Builder b,ObjectMapper m){client=b.build();mapper=m;}public ProviderType providerType(){return ProviderType.GENERIC_HTML;}
 public List<JobPostingCommand> fetchJobs(Company c){var cfg=new ProviderConfiguration(mapper,c.getProviderConfiguration());String url=Optional.ofNullable(cfg.text("careersUrl")).orElse(c.getCareerUrl());String item=cfg.required("jobSelector"),linkSel=Optional.ofNullable(cfg.text("jobLinkSelector")).orElse("a"),titleSel=cfg.required("titleSelector"),locSel=cfg.text("locationSelector");int max=Math.min(cfg.integer("maxPages",1),20);List<JobPostingCommand>out=new ArrayList<>();Set<String>seen=new HashSet<>();for(int page=1;page<=max;page++){String pageUrl=url.replace("{page}",String.valueOf(page));String html=GenericProviderSupport.retry(3,()->client.get().uri(pageUrl).retrieve().body(String.class));Document doc=Jsoup.parse(html,pageUrl);for(var e:doc.select(item)){String apply=GenericProviderSupport.attr(e,linkSel,"href"),title=GenericProviderSupport.value(e,titleSel),loc=locSel==null?null:GenericProviderSupport.value(e,locSel);if(apply==null||apply.isBlank()||title==null||title.isBlank()||!seen.add(apply))continue;out.add(new JobPostingCommand(Integer.toHexString(apply.hashCode()),c.getId(),title,loc,EmploymentTypeParser.fromKeyword(title),RemoteHeuristic.looksRemote(title,loc),null,null,null,e.text(),LocalDate.now(),apply));}if(!url.contains("{page}"))break;}return out;}
}
