package com.careeros.provider.infrastructure.generic;

import com.careeros.company.domain.*;import com.careeros.provider.domain.ProviderType;import com.fasterxml.jackson.databind.ObjectMapper;import org.junit.jupiter.api.Test;import org.springframework.test.web.client.MockRestServiceServer;import org.springframework.web.client.RestClient;import java.util.List;import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.test.web.client.match.MockRestRequestMatchers.requestTo;import static org.springframework.test.web.client.response.MockRestResponseCreators.withSuccess;import org.springframework.http.MediaType;
class GenericProvidersTest {
 @Test void extractsJobsFromConfiguredHtml(){var b=RestClient.builder();var server=MockRestServiceServer.bindTo(b).build();server.expect(requestTo("https://example.test/careers")).andRespond(withSuccess("<div class='job'><a href='/jobs/1'><b>Senior Engineer</b><i>Chicago</i></a></div>",MediaType.TEXT_HTML));var c=company();c.configureProvider(ProviderType.GENERIC_HTML,"{\"careersUrl\":\"https://example.test/careers\",\"jobSelector\":\".job\",\"jobLinkSelector\":\"a\",\"titleSelector\":\"b\",\"locationSelector\":\"i\"}",List.of());var jobs=new GenericHtmlProvider(b,new ObjectMapper()).fetchJobs(c);assertThat(jobs).singleElement().satisfies(j->{assertThat(j.title()).isEqualTo("Senior Engineer");assertThat(j.location()).isEqualTo("Chicago");});server.verify();}
 @Test void supportsRssAndAtomEntries(){var b=RestClient.builder();var server=MockRestServiceServer.bindTo(b).build();server.expect(requestTo("https://example.test/jobs.xml")).andRespond(withSuccess("<feed><entry><id>1</id><title>Staff Engineer</title><link href='https://example.test/1'/><summary>Java</summary><location>Remote</location></entry></feed>",MediaType.APPLICATION_XML));var c=company();c.configureProvider(ProviderType.GENERIC_RSS,"{\"feedUrl\":\"https://example.test/jobs.xml\"}",List.of());assertThat(new GenericRssProvider(b,new ObjectMapper()).fetchJobs(c)).singleElement().extracting(x->x.title()).isEqualTo("Staff Engineer");server.verify();}
 @Test void mapsNestedJsonFields(){var b=RestClient.builder();var server=MockRestServiceServer.bindTo(b).build();server.expect(requestTo("https://example.test/jobs.json")).andRespond(withSuccess("{\"data\":{\"jobs\":[{\"id\":\"a\",\"name\":\"Platform Engineer\",\"place\":\"Remote\",\"url\":\"https://example.test/a\"}]}}",MediaType.APPLICATION_JSON));var c=company();c.configureProvider(ProviderType.GENERIC_JSON,"{\"endpoint\":\"https://example.test/jobs.json\",\"itemsField\":\"data.jobs\",\"idField\":\"id\",\"titleField\":\"name\",\"locationField\":\"place\",\"urlField\":\"url\"}",List.of());assertThat(new GenericJsonProvider(b,new ObjectMapper()).fetchJobs(c)).singleElement().satisfies(j->{assertThat(j.title()).isEqualTo("Platform Engineer");assertThat(j.remote()).isTrue();});server.verify();}
 private Company company(){return Company.create("Example","https://example.test/careers",AtsType.OTHER,Priority.HIGH,true,null);}
}
